on: [push]

name: AzureBicepDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source codel'' np,l?'
        uses: actions/checkout@v2

      - name: Deploy Bicep Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
        
            az deployment sub create \
            --location 'eastus' \
            --name 'BicepLab1DeploymentRG' \
            --template-file 'biceptemplates/labs/lab01//main.bicep' \
            --verbose
