on: [push]

name: AzureBicepDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source codel'' np,l?'
        uses: actions/checkout@v2

      - name: Deploy Bicep Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group mlz-demo \
            --template-file armtemplates/storageaccount.json \
            --parameters storageAccountType=Standard_GRS
