on: [push]

name: AzureARMDeploy

jobs:
      deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Login to Azure gov cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREGOVCREDI }}
          environment: 'AzureUSGovernment'
    
      - name: Checkout source codel'
        uses: actions/checkout@v2

      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with:
          inlineScript: |
       az group create --location usgovvirginia --resource-group testrg3
