on: [push]

name: AzureBicepDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy Bicep Template
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az deployment sub create --location 'eastus' --name 'lab01' --template-file 'biceptemplates/labs/lab01/main.bicep' --parameters 'biceptemplates/labs/lab01/main.parameters.json' --verbose