on: [push]

name: AzureARMDeploy

jobs:
      deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Login to Azure gov cloud
  uses: azure/login@v2
  with:
    creds: ${{ secrets.AZUREGOVCREDI }}
    environment: 'AzureUSGovernment'
    enable-AzPSSession: true
    
      - name: Checkout source codel'
        uses: actions/checkout@v2

      - name: Deploy ARM Template
        uses: azure/CLI@v2
        with:
          inlineScript: |
       az group create --location usgovvirginia --resource-group testrg3
